HaiSanShop.WebApp/Controllers/QLDonHangController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaiSanShop.WebApp.Views.QLSanPham
{
    [Authorize(Roles = "QLDonDatHang")]
    public class QLDonHangController : Controller
    {
        private readonly HaiSanHopDbContext db = null;
        public QLDonHangController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: QLDonHang
        //DON HANG MOI
        public ActionResult Index()
        {
            var lstddh = db.dondathangs.Where(c => c.DaThanhToan == false && c.DaGiao == false).ToList();
            return View(lstddh);
           
        }
        public ActionResult ChuaNhanHang()
        {
            var lstddh = db.dondathangs.Where(c => c.DaThanhToan == true && c.DaGiao == false).ToList(); ;
            return View(lstddh);

        }


        public ActionResult HoanTat()
        {
            var lstddh = db.dondathangs.Where(c => c.DaThanhToan == true && c.DaGiao == true).ToList();
            return View(lstddh);
        }
        public ActionResult DuyetDon(int? id)
        {
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            DonDatHang ddh = db.dondathangs.SingleOrDefault(c => c.MaDDH == id);
            if (ddh == null)
            {
                return HttpNotFound();
            }

            ViewBag.lstchitiet = db.chitietdondathangs.Where(c => c.MaDDH == ddh.MaDDH).ToList(); 
            return View(ddh);
        }
        [HttpPost]
        public ActionResult DuyetDon(DonDatHang ddh)
        {
            DonDatHang ddhupdate = db.dondathangs.SingleOrDefault(c => c.MaDDH == ddh.MaDDH);
            ddhupdate.DaGiao = ddh.DaGiao;
            ddhupdate.DaThanhToan = ddh.DaThanhToan;
            ddhupdate.NgayGiao = DateTime.Now;
            db.SaveChanges();
            ViewBag.lstchitiet = db.chitietdondathangs.Where(c => c.MaDDH == ddh.MaDDH).ToList();
            return View(ddhupdate);
        }
    }
}

HaiSanShop.WebApp/Views/QLDonHang/ChuaNhanHang.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "ChuaNhanHang";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<center>
    <div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","QLDonHang")">Đơn Hàng Mới</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("ChuaNhanHang","QLDonHang")">Chưa Nhận Hàng</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("HoanTat","QLDonHang")">Hoàn Tất</a>
            </li>

        </ul>
    </div>
    <br /><br />
    <table class="table table-responsive ml-3">
        <thead>
            <tr>
                <th>Mã Đơn Đặt Hàng</th>
                <th>Khách Hàng</th>
                <th>Ngày Đặt</th>
                <th>Thanh Toán</th>
                <th>Giao Hàng</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() != 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaDDH</td>
                        <td>@item.KhachHangs.TenKH</td>
                        <td>@item.NgayDat.ToString("dd/MM/yyyy")</td>
                        <td>@item.DaThanhToan</td>
                        <td>@item.DaGiao</td>
                        <td><a class="btn btn-success" href="@Url.Action("DuyetDon","QLDonHang",new {@id=item.MaDDH })">Duyệt Đơn</a></td>
                    </tr>
                }

            }
            else
            {
                <tr>
                    <td colspan="6">
                        <h2 style="color:green"> chưa có đơn hàng  nào</h2>
                    </td>
                </tr>


            }
        </tbody>

    </table>
</center>

HaiSanShop.WebApp/Views/QLDonHang/DuyetDon.cshtml
@using HaiSanShop.Data.Entites
@model DonDatHang
@{
    ViewBag.Title = "DuyetDon";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<a href="@Url.Action("Index","QLDonHang")" class="btn btn-danger"> Quay Lại</a>
<br />
<br />
<div class="align-center">
    <h3 style="color:rebeccapurple">@ViewBag.thongbao</h3>
    @using (Html.BeginForm())
    {
        <div class="modal-content modal-open noidungdonhang">
            <table class="table">
                <tr>
                    <td>Mã Đơn :@Model.MaDDH @Html.Hidden("MaDDH", Model.MaDDH)</td>
                    <td>Khách Hàng: @Model.KhachHangs.TenKH</td>
                </tr>
                <tr>
                    <td>Giao Hàng  :@Html.CheckBox("DaGiao", Model.DaGiao)</td>
                    <td>Thanh Toán :@Html.CheckBox("DaThanhToan",Model.DaThanhToan)</td>
                    
                </tr>
            </table>
            <br />
            <h3>Chi Tiết Đơn Hàng</h3>
            <br />
            <table class="table table-active">
                <thead>
                    <tr>
                        <th>Sản Phẩm</th>
                        <th>Hình Ảnh</th>
                        <th>Số Lượng</th>
                        <th>Đơn Giá</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        IEnumerable<ChiTietDonDatHang> lstchitiet = ViewBag.lstchitiet as IEnumerable<ChiTietDonDatHang>;
                        int? sl = 0;
                        decimal? tt = 0;
                    }
                    @foreach (var item in lstchitiet)
                    {
                        sl += item.SoLuong;
                        tt += item.DonGia * item.SoLuong;
                        <tr>
                            <td>@item.SanPhams.TenSP</td>
                            <td><img src="~/Content/ImageSanPham/@item.SanPhams.HinhAnh" height="100" width="80" /></td>
                            <td>@item.SoLuong</td>
                            <td>@item.DonGia.ToString("#,##")VNĐ</td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2">Tổng Số Lượng : @sl</td>
                        <td colspan="2">Tổng Tiền :@tt.Value.ToString("#,##")</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br /><br />
        <input class="btn btn-primary" id="btn_in" type="button" value="In Đơn Hàng" />
        <input class="btn btn-success" id="btn_up" type="submit" value="Cập Nhập" />
    }
</div>

<script>
   
    
    $("#btn_in").click(function () {
        var content = $(".noidungdonhang").html();
        InDonHang(content);
    })
    function InDonHang(content) {
        var printWindown = window.open('', '', 'height=400,width=800');
            printWindown.document.write("<html><head><title>IN ĐƠN HÀNG</title></header>");
            printWindown.document.write("<body>");
            printWindown.document.write(content);
            printWindown.document.write("</body></html>");
            printWindown.document.close();
            printWindown.print();

    };


</script>

HaiSanShop.WebApp/Views/QLDonHang/HoanTat.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "HoanTat";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<center>
    <div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","QLDonHang")">Đơn Hàng Mới</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ChuaNhanHang","QLDonHang")">Chưa Nhận Hàng</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("HoanTat","QLDonHang")">Hoàn Tất</a>
            </li>

        </ul>
    </div>
    <br /><br />
    <table class="table table-responsive ml-3">
        <thead>
            <tr>
                <th>Mã Đơn Đặt Hàng</th>
                <th>Khách Hàng</th>
                <th>Ngày Đặt</th>
                <th>Thanh Toán</th>
                <th>Giao Hàng</th>
                <th>Ngày Giao</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() != 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaDDH</td>
                        <td>@item.KhachHangs.TenKH</td>
                        <td>@item.NgayDat.ToString("dd/MM/yyyy")</td>
                        <td>@item.DaThanhToan</td>
                        <td>@item.DaGiao</td>
                        <td>@item.NgayGiao.ToString("dd/MM/yyyy")</td>
                        <td><a class="btn btn-success" href="@Url.Action("DuyetDon","QLDonHang",new {@id=item.MaDDH })">Duyệt Đơn</a></td>
                    </tr>
                }

            }
            else
            {

                <tr>
                    <td colspan="6">
                        <h2 style="color:green"> chưa có đơn hàng  nào</h2>
                    </td>
                </tr>

            }
        </tbody>

    </table>
</center>

HaiSanShop.WebApp/Views/QLDonHang/Index.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Đơn Hàng Mới";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<center>
    <div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Index","QLDonHang")">Đơn Hàng Mới</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ChuaNhanHang","QLDonHang")">Chưa Nhận Hàng</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("HoanTat","QLDonHang")">Hoàn Tất</a>
            </li>

        </ul>
    </div>
    <br /><br />
    <table class="table table-responsive ml-3">
        <thead>
            <tr>
                <th>Mã Đơn Đặt Hàng</th>
                <th>Ngày Đặt</th>
                <th>Khách Hàng</th>
                <th>Thanh Toán</th>
                <th>Giao Hàng</th>
            </tr>
        </thead>
        <tbody>

            @if (Model.Count() != 0)
            {
                foreach (var item in Model)
                { 
                        <tr>
                            <td>@item.MaDDH</td>
                            <td>@item.NgayDat.ToString("dd/MM/yyyy")</td>
                            <td>@item.KhachHangs.TenKH
                            <td>@item.DaThanhToan</td>
                            <td>@item.DaGiao</td>
                            <td><a class="btn btn-success" href="@Url.Action("DuyetDon","QLDonHang",new {@id=item.MaDDH })">Duyệt Đơn</a></td>
                        </tr>
                }

            }
            else
            {

            <tr>
                <td colspan="6">
                    <h2 style="color:green"> chưa có đơn hàng mới nào</h2>
                </td>
            </tr>

            }
        </tbody>

    </table>
</center>