HaiSanShop.WebApp/Controllers/BangGiaController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaiSanShop.WebApp.Controllers
{
    public class BangGiaController : Controller
    {

        private readonly HaiSanHopDbContext db = null;
        public BangGiaController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: BangGia
        public ActionResult Index()
        {
            var list = db.BangGias.ToList();
            return View(list);
        }
        [HttpPost]
        public ActionResult SuaGia(int? Ma, int? Gia, string Ten)
        {
            bool result = false;
            if (Ma == null || Gia == null)
            {
                result = false;
            }
            var banggia = db.BangGias.SingleOrDefault(c => c.Ma == Ma);
            if (banggia != null)
            {
                banggia.Gia = int.Parse(Gia.ToString());
                banggia.TenSanPham = Ten;
                db.SaveChanges();
                result = true;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult XoaBangGia(int Ma)
        {
            bool result = false;
            var bg= db.BangGias.SingleOrDefault(c => c.Ma == Ma);
            if (bg != null)
            {
                db.BangGias.Remove(bg);
                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public void Them(BangGia bg )
        {
            db.BangGias.Add(bg);
            db.SaveChanges();
        }
    }
}

HaiSanShop.WebApp/Controllers/KhachHangController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaiSanShop.WebApp.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly HaiSanHopDbContext db= null;
        public KhachHangController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: KhachHang
        public ActionResult ThongTin(int? MaKH)
        {
            if (MaKH == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var tv = db.thanhviens.SingleOrDefault(c => c.MaTV == MaKH);
            if(tv== null)
            {
                return HttpNotFound();
            }
            return View(tv);
        }
        public ActionResult SuaTT(ThanhVien  tv)
        {
            string result = "Sửa Thất Bại";
            var tvs = db.thanhviens.SingleOrDefault(c => c.MaTV == tv.MaTV);
            if(tvs!=null)
            {
                tvs.HoTen = tv.HoTen;
                tvs.SDT = tv.SDT;
                tvs.DiaChi = tv.DiaChi;
                db.SaveChanges();
                    result = "Sửa thành Công";
                
                
            }
            
            return Json(result,JsonRequestBehavior.AllowGet);
        }
        public ActionResult SuaMK(ThanhVien tv)
        {
            string result = "Sửa Thất Bại";
            var tvs = db.thanhviens.SingleOrDefault(c => c.MaTV == tv.MaTV);
            if (tvs != null)
            {
                tvs.MatKhau = tv.MatKhau;
                db.SaveChanges();
                result = "Sửa Thành Công";


            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

HaiSanShop.WebApp/Controllers/QLBlogController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace HaiSanShop.WebApp.Controllers
{
    public class QLBlogController : Controller
    {
        private readonly HaiSanHopDbContext db = null;
        public QLBlogController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: QLBlog
        public ActionResult Index(int? page)
        {
            int pagesize = 10;
            int pagenumber = (page ?? 1);
            var list = db.Blogs.ToList();
            return View(list.ToPagedList(pagenumber,pagesize));
        }
        [HttpGet]
        public ActionResult CreateBlog()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateBlog(Blog b, HttpPostedFileBase HinhAnh)
        {

            if (HinhAnh != null)
            {
                if (HinhAnh.ContentLength > 0)
                {
                    if (HinhAnh.ContentType != "image/jpeg" && HinhAnh.ContentType != "image/png" && HinhAnh.ContentType != "image/jfif" && HinhAnh.ContentType != "image/jpg")
                    {
                        ViewBag.thongbaoUpload = "Định dạng hình ảnh không hợp lệ , vui lòng kiểm tra lại";

                    }
                    else
                    {
                        // kiểm tra hình ảnh đã tồn tại chưa
                        var filename = Path.GetFileName(HinhAnh.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/ImageBlog"), filename);
                        if (System.IO.File.Exists(path))
                        {
                            ViewBag.thongbaoUpload = "Hình ảnh  đã tồn tại, hãy chọn ảnh khác";

                        }
                        else HinhAnh.SaveAs(path);
                        b.AnhMinhHoa = filename;

                    }
                }

            }
            if (ModelState.IsValid)
            {
                b.NgayTao = DateTime.Now;
                db.Blogs.Add(b);

                db.SaveChanges();
                return RedirectToAction("Index");

            }

            else
            {
                ViewBag.thongbao = "Tạo Blog Thất bại";
                return View();
            }
        }
        [HttpPost]
        public ActionResult XoaBlog(int MaBlog)
        {
            bool result = false;
            var blog = db.Blogs.SingleOrDefault(c => c.Ma == MaBlog);
            if (blog != null)
            {
                db.Blogs.Remove(blog);
                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult SuaBlog(int? MaBlog)
        {
            if (MaBlog == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var blog = db.Blogs.SingleOrDefault(c => c.Ma == MaBlog);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaBlog(Blog bl, HttpPostedFileBase HinhAnh)
        {
            var blog = db.Blogs.SingleOrDefault(c => c.Ma == bl.Ma);

            if (HinhAnh != null)
            {
                if (HinhAnh.ContentLength > 0)
                {
                    if (HinhAnh.ContentType != "image/jpeg" && HinhAnh.ContentType != "image/png" && HinhAnh.ContentType != "image/jfif" && HinhAnh.ContentType != "image/jpg")
                    {
                        ViewBag.ThongBaoUpload = "Định dạng hình ảnh không hợp lệ , vui lòng kiểm tra lại";

                    }
                    else
                    {
                        // kiểm tra hình ảnh đã tồn tại chưa
                        var filename = Path.GetFileName(HinhAnh.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/ImageSanPham"), filename);
                        if (System.IO.File.Exists(path))
                        {
                            ViewBag.ThonBaoUpload = "Hình ảnh  đã tồn tại, hãy chọn ảnh khác";

                        }
                        else HinhAnh.SaveAs(path);
                        blog.AnhMinhHoa = filename;

                    }
                }

            }
            
            if (ModelState.IsValid)
            {
                blog.TieuDe = bl.TieuDe;
                blog.VanTat = bl.VanTat;
                blog.Hien = bl.Hien;
                blog.DaXoa = bl.DaXoa;
               
                if (db.SaveChanges() > 0)
                {
                   
                    return RedirectToAction("Index");
                }

            }
            else
            {
                ViewBag.thongbao = "Dữ Liệu Update không hợp lệ";
                return View(bl);
            }



            return View(bl);
        }
    }
}

HaiSanShop.WebApp/Controllers/SanPhamController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Application.Public;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace HaiSanShop.WebApp.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly SanPhamPublic db = null;
        public SanPhamController()
        {
            db = new SanPhamPublic();
        }
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult SanPhamHomePartial()
        {

            return PartialView();
        }
        public ActionResult DanhMuc(int? MaLoai, int? MaDM, int? page)
        {
            if(MaLoai==null || MaDM == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var list = db.GetListDMAndLoai(MaLoai, MaDM);
            if (list == null)
            {
                return HttpNotFound();
            }
            int pagesize = 6;
            int pagenumber = (page ?? 1);
            ViewBag.maloai = MaLoai;
            ViewBag.madm = MaDM;
            ViewBag.tenloai = db.gettenloai(MaDM);
            return View(list.ToPagedList(pagenumber,pagesize));
        }
        public ActionResult ChiTiet(int? MaSP)
        {
            if (MaSP == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            if (db.getDetail(MaSP) == null)
            {
                return HttpNotFound();

            }
            return View(db.getDetail(MaSP));
        }
        [HttpGet]
        public ActionResult Search(string keyword, int? page)
        {
            if(Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pagesize = 9;
            int pagenumber = (page ?? 1);
            ViewBag.key = keyword;
            return View(db.Search(keyword).ToPagedList(pagenumber,pagesize));
        }
        [HttpPost]
        public ActionResult Search(string keyword, FormCollection f)
        {
            
            return View(db.Search(keyword));
        }

    }
}

HaiSanShop.WebApp/Views/Shared/HeadertopPartial.cshtml
@using HaiSanShop.Data.Entites
<div class="header-bot">
    <div class="header-bot_inner_wthreeinfo_header_mid">
        <!-- header-bot-->
        <div class="col-md-4 logo_agile">
            <h1>
                <a href="@Url.Action("Index","Home")">
                    <span>H</span>ải Sản
                    <span>S</span>ầm Sơn
                    <img src="~/Content/images/logo2.png" alt=" ">
                </a>
            </h1>
        </div>
        <!-- header-bot -->
        <div class="col-md-8 header">
            <!-- header lists -->
            <ul>

                <li style="width:300px">

                </li>
                <li>
                    <span class="fa fa-phone" aria-hidden="true"></span>0862560197
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    if (Session["DangNhap"] != null && Session["DangNhap"] != "")
                    {

                        ThanhVien thanhVien = Session["DangNhap"] as ThanhVien;

                        <li class="w-100"><a href="@Url.Action("ThongTin","KhachHang",new {@MaKH=thanhVien.MaTV})"><h4><i class="fa fa-user"></i>  @HttpContext.Current.User.Identity.Name</h4> </a></li>
                        @Html.ActionLink("Đăng Xuất", "DangXuat", "Home")
                    }
                    else
                    {
                        <li class="w-100"><a href="#"><h4><i class="fa fa-user"></i>  @HttpContext.Current.User.Identity.Name</h4> </a></li>
                        @Html.ActionLink("Đăng Xuất", "DangXuat", "Home")
                    }


                }
                else
                {
                    <li>
                        <a href="#" data-toggle="modal" data-target="#myModal1">
                            <span class="fa fa-unlock-alt" aria-hidden="true"></span>Đăng Nhập
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("DangKy","Home")">
                            <span class="fa fa-pencil-square-o" aria-hidden="true"></span>Đăng Ký
                        </a>
                    </li>
                }


            </ul>
            <!-- //header lists -->
            <!--Tìm Kiếm -->
            <div class="agileits_search">
                @using (Html.BeginForm("Search", "SanPham", FormMethod.Get))
                {
                    <input name="keyword" type="search" placeholder="Tôi Có Thể Giúp Gì Cho Bạn ?" required="">
                    <button type="submit" class="btn btn-default" aria-label="Left Align">
                        <span class="fa fa-search" aria-hidden="true"> </span>
                    </button>
                }


            </div>
            <!-- //search -->
            <!-- Img Gior Hàng -->
            <div class="top_nav_right">
                <div class="wthreecartaits wthreecartaits2 cart cart box_1">

                    <button class="w3view-cart" onclick="btncart()" type="submit" name="submit" value="">
                        <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
            <script>
                    var btncart = function () {
                        window.location.href = "/GioHang/XemGioHang";
                    }
            </script>



            <!-- //cart details -->
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<!--Đăng Nhập -->
<!-- Modal1 -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body modal-body-sub_agile">
                <div class="main-mailposi">
                    <span class="fa fa-envelope-o" aria-hidden="true"></span>
                </div>
                <div class="modal_body_left modal_body_left1">
                    <h3 class="agileinfo_sign">Đăng Nhập </h3>
                    <p>
                        Đăng Ký Thành Viên Ngay Bây Giờ Để Có Thể Nhận Được Nhưng Ưu Đãi Khi Mua Hàng
                        <a href="#" data-toggle="modal" data-target="#myModal2">
                            Đăng Ký Ngay
                        </a>
                    </p>
                    @using (Ajax.BeginForm(new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "thongbao" }))

                    {
                        <div class="styled-input agile-styled-input-top">
                            <input type="text" placeholder="Tài Khoản" name="TaiKhoan" required="">
                        </div>
                        <div class="styled-input">
                            <input type="password" placeholder="Mật Khẩu" name="MatKhau" required="">
                        </div>
                        <h3 style="color:green" id="thongbao"></h3>
                        <input type="submit" class="btnlogin" value="Đăng Nhập">
                    }

                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- //Modal content-->
    </div>
</div>



<script type="text/javascript">
    $(document).ready(function () {
        
        
        $(".btnlogin").click(function () {
            debugger
            

            //Lấy toàn bộ dữ liệu trong Form
            var Data= $('form#form0').serialize();

            //Sử dụng phương thức Ajax.
            $.ajax({
               
                type: "POST", //Sử dụng kiểu gửi dữ liệu POST
                url: "/Home/DangNhap", //gửi dữ liệu sang trang data.php
                data: Data, //dữ liệu sẽ được gửi
                success: function (result)  // Hàm thực thi khi nhận dữ liệu được từ server
                {
                    debugger
                    if (result == 'false') {
                         $('#thongbao').html("Đăng Nhập Thất Bại! Vui Lòng kiểm Tra Lại Thông Tin");
                    } else {

                        window.location.reload();
                    }
                }
            });
            return false;
        });
    });
</script>

HaiSanShop.WebApp/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Quản Trị Website</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <link href="~/ContentAdmin/vendor/fontawesome-free/css/all.css" rel="stylesheet" />
    <link href="~/ContentAdmin/css/sb-admin-2.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Admin")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Quản Trị  <sup>Web</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Admin")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Quản Trị</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                <h5> Public Manage</h5>
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa fa-magic"></i>
                    <span>Sản Phẩm</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="@Url.Action("Index","QLSanPham")">Danh Sách </a>
                        <a class="collapse-item" href="@Url.Action("HangHet","QLSanPham")">Nhập Hàng</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">

                <a class="nav-link collapsed " href="@Url.Action("Index","QLDonHang")">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Đơn Hàng</span>
                </a>

            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#info" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa fa-info"></i>
                    <span>Thêm</span>
                </a>
                <div id="info" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="@Url.Action("Index","BangGia")">Giá Niêm Yết </a>
                        <a class="collapse-item" href="@Url.Action("Index","QLBlog")">Blog</a>

                    </div>
                </div>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                <h5> Private Manage</h5>
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Thành Viên</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Thành Viên</h6>
                        <a class="collapse-item" href="@Url.Action("Index","QLThanhVien")">Thành Viên</a>
                        <a class="collapse-item" href="@Url.Action("Quyen","QLThanhVien")">Phân Quyền</a>

                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@HttpContext.Current.User.Identity.Name</span>
                                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Thông Tin
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Đăng Xuất
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bạn Muốn Thoát Khỏi Trang Quản Trị?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Sau Khi Chọn Đăng Xuất , Bạn Sẽ Thoát khỏi Trang Này Hoàn Toàn</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="@Url.Action("DangXuat","Admin")">Đăng Xuất</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/ContentAdmin/vendor/jquery/jquery.min.js"></script>
    <script src="~/ContentAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/ContentAdmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/ContentAdmin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/ContentAdmin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/ContentAdmin/js/demo/chart-area-demo.js"></script>
    <script src="~/ContentAdmin/js/demo/chart-pie-demo.js"></script>

</body>

</html>

HaiSanShop.WebApp/Views/Shared/dropdowlistsp.cshtml
@if (ViewBag.lstsp != null)
{
    <option value="">--- Lựa Chọn Sản Phẩm--</option>
    foreach (var item in ViewBag.lstsp)
    {
        <option value="@item.Value">@item.Text</option>
    }
}