HaiSanShop.WebApp/Controllers/BangGiaController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaiSanShop.WebApp.Controllers
{
    public class BangGiaController : Controller
    {

        private readonly HaiSanHopDbContext db = null;
        public BangGiaController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: BangGia
        public ActionResult Index()
        {
            var list = db.BangGias.ToList();
            return View(list);
        }
        [HttpPost]
        public ActionResult SuaGia(int? Ma, int? Gia, string Ten)
        {
            bool result = false;
            if (Ma == null || Gia == null)
            {
                result = false;
            }
            var banggia = db.BangGias.SingleOrDefault(c => c.Ma == Ma);
            if (banggia != null)
            {
                banggia.Gia = int.Parse(Gia.ToString());
                banggia.TenSanPham = Ten;
                db.SaveChanges();
                result = true;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult XoaBangGia(int Ma)
        {
            bool result = false;
            var bg= db.BangGias.SingleOrDefault(c => c.Ma == Ma);
            if (bg != null)
            {
                db.BangGias.Remove(bg);
                db.SaveChanges();
                result = true;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public void Them(BangGia bg )
        {
            db.BangGias.Add(bg);
            db.SaveChanges();
        }
    }
}

HaiSanShop.WebApp/Controllers/BlogController.cs
using HaiSanSamSon.Data.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;


namespace HaiSanShop.WebApp.Controllers
{
    public class BlogController : Controller
    {
        private HaiSanHopDbContext db = null;
        public BlogController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: Blog
        public ActionResult Index(int? page)
        {
            var list = db.Blogs.Where(c => c.DaXoa == false && c.Hien == true).ToList();
            int pagesize = 10;
            int pagenumber = (page ?? 1);
            return View(list.ToPagedList(pagenumber,pagesize));
        }
        public ActionResult ViewBlog(int? Ma)
        {
            if(Ma== null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var blog = db.Blogs.SingleOrDefault(c => c.Ma == Ma);
            if(blog== null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }
        
    }
}

HaiSanShop.WebApp/Controllers/HomeController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Application.Public;
using HaiSanShop.Data.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HaiSanShop.WebApp.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly SanPhamPublic db= null;
        public HomeController()
        {
            db = new SanPhamPublic();
        }
        public ActionResult Index()
        {
            
            ViewBag.spmuoi = db.GetLoai(3, 3);

            ViewBag.spvo = db.GetLoai(4, 3);
            
            ViewBag.sptuoisong = db.GetLoai(2, 3);

            ViewBag.spdokho = db.GetLoai(1, 3);
            return View();
        }
        [ChildActionOnly]
        public ActionResult menutop()
        {
            var list = db.GetAllSP();
            return PartialView(list);
        }

        [HttpPost]
        public ActionResult DangNhap(ThanhVien tv)
        {
            using (HaiSanHopDbContext db = new HaiSanHopDbContext())
            {
                string tk = tv.TaiKhoan;
                string mk = tv.MatKhau;
                var tvlogin = db.thanhviens.SingleOrDefault(c => c.TaiKhoan == tk && c.MatKhau == mk);
                string result = "";
                if (tvlogin != null)
                {
                    IEnumerable<PhanQuyen> lstquyen = db.phanquyens.Where(c => c.MaLoaiTV == tvlogin.MaLoaiTV).ToList();
                    string Quyen = "";

                    if (lstquyen.Count() != 0)
                    {
                        foreach (var item in lstquyen)
                        {
                            var q = item.Quyens.MaQuyen.ToString();
                            Quyen += q + ",";
                        }
                        Quyen = Quyen.Substring(0, Quyen.Length - 1);


                    }
                    PhanQuyen(tvlogin.TaiKhoan.ToString(), Quyen);
                    Session["dangnhap"] = tvlogin;
                    
                    result = "true";
                }
                else
                {
                    result = "false";
                    
                }

                return Json(result, JsonRequestBehavior.AllowGet);
            }
                

        }
        public void PhanQuyen(string tk, string quyen)
        {
            FormsAuthentication.Initialize();
            var ticket = new FormsAuthenticationTicket(1,
                                             tk,//Tài Khoản Đăng Nhập
                                             DateTime.Now,
                                             DateTime.Now.AddHours(3),
                                             false,//cho luu lai lan dang nhap
                                             quyen,//quyen cua tk dang nhap
                                             FormsAuthentication.FormsCookiePath);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, 
                FormsAuthentication.Encrypt(ticket));
            if (ticket.IsPersistent) cookie.Expires = ticket.Expiration;
            Response.Cookies.Add(cookie);
        }
        public ActionResult DangXuat()
        {
            Session["DangNhap"] = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

        public ActionResult DangKy()
        {
          
            return View();
        }
        
        [HttpPost]
        public ActionResult DangKy(ThanhVien tv)
        {
            using (HaiSanHopDbContext db = new HaiSanHopDbContext())
            {

                if (ModelState.IsValid)
                {
                    var user = db.thanhviens.SingleOrDefault(c => c.TaiKhoan == tv.TaiKhoan);
                    if(user!= null)
                    {
                        ViewBag.thongbao = "Tên Tài Khoản Đã Tồn Tại , Hãy Chọn Tên Khác";
                        Session["dangky"] = tv;
                        return View();
                    }

                    tv.MaLoaiTV = 4;
                    ViewBag.thongbao = "Đăng Ký Thành Viên Thành Công . Hãy Đăng Nhập Để Tiếp Tục Mua Hàng ";
                    db.thanhviens.Add(tv);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.thongbao = "Thêm Thông Tin Thất Bại , Vui Lòng Kiểm Tra Lại";
                }

                return View();
            }
        }
        public ActionResult GioiThieu()
        {
            return View();
        }
        public ActionResult BangGia()
        {
            using (HaiSanHopDbContext db =new HaiSanHopDbContext())
            {
                var bg = db.BangGias.ToList();
                return View(bg);
            }
              

        }
        public ActionResult TrangPhanHoi()
        {
            return View();
        }
        public ActionResult contact()
        {
            return View();
        }
    }
}

HaiSanShop.WebApp/Controllers/SanPhamController.cs
using HaiSanSamSon.Data.EF;
using HaiSanShop.Application.Public;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace HaiSanShop.WebApp.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly SanPhamPublic db = null;
        public SanPhamController()
        {
            db = new SanPhamPublic();
        }
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult SanPhamHomePartial()
        {

            return PartialView();
        }
        public ActionResult DanhMuc(int? MaLoai, int? MaDM, int? page)
        {
            if(MaLoai==null || MaDM == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var list = db.GetListDMAndLoai(MaLoai, MaDM);
            if (list == null)
            {
                return HttpNotFound();
            }
            int pagesize = 6;
            int pagenumber = (page ?? 1);
            ViewBag.maloai = MaLoai;
            ViewBag.madm = MaDM;
            ViewBag.tenloai = db.gettenloai(MaDM);
            return View(list.ToPagedList(pagenumber,pagesize));
        }
        public ActionResult ChiTiet(int? MaSP)
        {
            if (MaSP == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            if (db.getDetail(MaSP) == null)
            {
                return HttpNotFound();

            }
            return View(db.getDetail(MaSP));
        }
        [HttpGet]
        public ActionResult Search(string keyword, int? page)
        {
            if(Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pagesize = 9;
            int pagenumber = (page ?? 1);
            ViewBag.key = keyword;
            return View(db.Search(keyword).ToPagedList(pagenumber,pagesize));
        }
        [HttpPost]
        public ActionResult Search(string keyword, FormCollection f)
        {
            
            return View(db.Search(keyword));
        }

    }
}

HaiSanShop.WebApp/Controllers/TestController.cs
using HaiSanSamSon.Data.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaiSanShop.WebApp.Controllers
{
    public class TestController : Controller
    {
        private HaiSanHopDbContext db = null;
        public TestController()
        {
            db = new HaiSanHopDbContext();
        }
        // GET: Test
        public ActionResult Index()
        {
            var lst = db.SanPhams.ToList();
            ViewBag.lst = lst;
            return View();
        }
    }
}

HaiSanShop.WebApp/Views/Home/BangGia.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<BangGia>
@{
    ViewBag.Title = "BangGia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-secondary">Bảng Giá Niêm Yết</h2>
<br /><br />
<table class="table table-sm">
    <thead>
        <tr>
            <th scope="col">Mã</th>
            <th scope="col">Tên</th>
            <th scope="col">Giá Niêm Yết</th>
            
        </tr>
    </thead>
    <tbody>
       
        @foreach(var item in Model)
        {
            int i = 1;
            <tr>
                <th scope="row">@i</th>
                <td>@item.TenSanPham</td>
                <td>@item.Gia.ToString("#,##")VNĐ</td>
                 
            </tr>
        }


    </tbody>
</table>

HaiSanShop.WebApp/Views/Home/DangKy.cshtml
@using HaiSanShop.Data.Entites
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DangKy", "Home", FormMethod.Post))
{
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-body modal-body-sub_agile">
                <div class="main-mailposi">
                    <span class="fa fa-envelope-o" aria-hidden="true"></span>
                </div>
                <div class="modal_body_left modal_body_left1">
                    <h3 class="agileinfo_sign">Đăng Ký</h3>
                    <p>

                        <h3 style="color:red">@ViewBag.thongbao</h3>

                    </p>
                    @if (Session["dangky"] != null && Session["dangky"] != "")
                    {
                        ThanhVien thanhVien = Session["dangky"] as ThanhVien;
                        <form action="#" method="post">
                            <div class="styled-input agile-styled-input-top">
                                <input type="text" placeholder="Họ Tên" value="@thanhVien.HoTen" name="HoTen" required="">
                            </div>
                            <div class="styled-input">
                                <input type="text" placeholder="Tài Khoản" value="@thanhVien.TaiKhoan" name="TaiKhoan" id="taikhoan" required="">
                                <span id="thongbao" style="color:red"></span>
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Mật Khẩu" name="MatKhau" id="password" required="">
                            </div>

                            <div class="styled-input">
                                <input type="text" placeholder="Số Điện Thoại" value="@thanhVien.SDT" name="SDT" required="">
                            </div>
                            <div class="styled-input">
                                <textarea placeholder="Địa Chỉ" class="form-control" name="DiaChi" id="diachi" required="">@thanhVien.DiaChi</textarea>
                            </div>
                            <input type="submit" id="btndk" value="Đăng Ký">
                        </form>
                    }
                    else
                    {
                        <form action="#" method="post">
                            <div class="styled-input agile-styled-input-top">
                                <input type="text" placeholder="Họ Tên" name="HoTen" required="">
                            </div>
                            <div class="styled-input">
                                <input type="text" placeholder="Tài Khoản" name="TaiKhoan" id="taikhoan" required="">
                                <span id="thongbao" style="color:red"></span>
                            </div>
                            <div class="styled-input">
                                <input type="password" placeholder="Mật Khẩu" name="MatKhau" id="password" required="">
                            </div>

                            <div class="styled-input">
                                <input type="text" placeholder="Số Điện Thoại" name="SDT" required="">
                            </div>
                            <div class="styled-input">
                                <textarea placeholder="Địa Chỉ" class="form-control" name="DiaChi" id="diachi" required=""></textarea>
                            </div>
                            <input type="submit" id="btndk" value="Đăng Ký">
                        </form>
                    }


                </div>
            </div>
        </div>
        <!-- //Modal content-->
    </div>
}

HaiSanShop.WebApp/Views/Home/GioiThieu.cshtml
@{
    ViewBag.Title = "GioiThieu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Giới thiệu về HaiSanSamSon</h2>
<h3><span>
    <br />
    HaiSanSamSon (HaiSanSamSon.vn) kính chào Quý khách. Chúc Quý khách dồi dào sức khỏe, nhiều may mắn và thành đạt ! Rất cảm ơn vì đã ghé thăm website của chúng tôi.
    <br /><br />
    chúng tôi luôn đặt chất lượng lên hàng đầu , vì thế chúng tôi luôn chọn nhập những 
        loại hải sản tốt nhất để có thể cung cấp cho quý khách

</span></h3>

HaiSanShop.WebApp/Views/Home/Index.cshtml
@using  HaiSanShop.Data.Entites
@model IEnumerable<SanPham>
@{
    ViewBag.Title = "Home Page";
}
<h3 class="tittle-w3l">
    <span class="heading-style">
        <i></i>
        <i></i>
        <i></i>
        <i></i>
        <i></i>
    </span>
</h3>
@{
    IEnumerable<SanPham> spts = ViewBag.sptuoisong as IEnumerable<SanPham>;
    IEnumerable<SanPham> dokho = ViewBag.spdokho as IEnumerable<SanPham>;
    IEnumerable<SanPham> dovo = ViewBag.spvo as IEnumerable<SanPham>;
    IEnumerable<SanPham> domuoi = ViewBag.spmuoi as IEnumerable<SanPham>;

}
<div class="wrapper">
    <!-- Hàng Tươi Sống -->
    <div class="product-sec1">
        <h3 class="heading-tittle">Đồ Tươi Sống</h3>
        @Html.Partial("~/Views/SanPham/SanPhamHomePartial.cshtml", spts)
    </div>
    <!-- //first section (nuts) -->
    <!-- second section (nuts special) -->
    <div class="product-sec1 product-sec2">
        <div class="col-xs-9 effect-bg">
            <h3 class="">Đồ Tươi Sống</h3>
            <h6>Hải Sản Khô đúng chuẩn</h6>
            <p>Giảm 10% Khi Là Khách Vip</p>
        </div>
        <h3 class="w3l-nut-middle">Chất &amp;Lượng</h3>

        <div class="clearfix"></div>
    </div>
    <!-- //second section (nuts special) -->
    <!-- Sản Phẩm Đồ Khô-->
    <div class="product-sec1">
        <h3 class="heading-tittle">Đồ Khô</h3>
        @Html.Partial("~/Views/SanPham/SanPhamHomePartial.cshtml", dokho)
    </div>
    <!-- //third section (oils) -->
    <!-- Đồ có vỏ -->
    <div class="product-sec1">
        <h3 class="heading-tittle">Hải Sản Có Vỏ</h3>
        @Html.Partial("~/Views/SanPham/SanPhamHomePartial.cshtml", dovo)
    </div>
    <!-- //fourth section (noodles) -->
    <!-- //third section (oils) -->
    <!-- Hải Sản Đã Chế Biến -->
    <div class="product-sec1">
        <h3 class="heading-tittle">Hải Sản Đã Chế Biến</h3>
        @Html.Partial("~/Views/SanPham/SanPhamHomePartial.cshtml", domuoi)
    </div>
    <!-- //fourth section (noodles) -->

</div>

HaiSanShop.WebApp/Views/Home/Menutop.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<SanPham>


<div class="ban-top">
    <div class="container">
        <div class="btn-group agileits-navi_search h6">
            <a class="btn btn-success dropdown-toggle"  data-toggle="dropdown" href="#">
               Lựa Chọn Mục Sản Phẩm
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" style="width:300px; font-size:16px">
                @foreach (var group in Model.GroupBy(c => c.LoaiSanPhams)) //loại sản phẩm ở đây nhớ ko nhầm vừa nó ko lấy được dữ liệu nên ko thể phân theo loaisp được
                {
                    if (group.Key != null)
                    {
                        <li style="padding: 0px 5px"><h3 class=" label label-info" >@group.Key.TenLoai</h3></li>
                        foreach (var item in group.GroupBy(c=>c.DanhMucSanPhams))
                        {
                            if (item.Key != null)
                            {
                                <li style="padding: 0px 20px" class="bor">
                                  <a href="@Url.Action("DanhMuc","SanPham",new {@MaLoai =group.Key.MaLoaiSP,@MaDM=item.Key.MaDM})">
                                         @item.Key.TenDanhMuc</a>
                                   @*@Html.Action("DanhMuc", "SanPham", new {@MaLoai = group.Key.MaLoaiSP,@MaDM =item.Key.MaDM })*@
                                   
                                </li>
                            }
                        }
                    }

                }

            </ul>
        </div>
        <div class="top_nav_left">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav menu__list">
                            <li class="active">

                                @Html.ActionLink("Trang Chủ", "Index", new { }, new { @class = "nav-stylehead" })
                            </li>
                            <li class="">

                                @Html.ActionLink("Giới Thiệu", "GioiThieu", new { }, new { @class = "nav-stylehead" })
                            </li>

                            <li class="">
                                @Html.ActionLink("Bảng Giá", "BangGia", new { }, new { @class = "nav-stylehead" })
                            </li>
                            <li class="">
                                @Html.ActionLink("Blog Chế Biến", "Index","Blog", new { }, new { @class = "nav-stylehead" })
                            </li>
                            <li class="">
                                <a class="nav-stylehead" href="@Url.Action("contact","Home")">Liên Hệ</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

HaiSanShop.WebApp/Views/Home/Test.cshtml
@using HaiSanShop.Data.Entites
@model IEnumerable<SanPham>

<a href="#" data-toggle="modal" data-target="#myModal1">
    <span class="fa fa-unlock-alt" aria-hidden="true"></span>Đăng Nhập
</a>
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body modal-body-sub_agile">
                <div class="main-mailposi">
                    <span class="fa fa-envelope-o" aria-hidden="true"></span>
                </div>
                <div class="modal_body_left modal_body_left1">
                    <h3 class="agileinfo_sign">Đăng Nhập </h3>
                    <p>
                        Đăng Ký Thành Viên Ngay Bây Giờ Để Có Thể Nhận Được Nhưng Ưu Đãi Khi Mua Hàng
                        <a href="#" data-toggle="modal" data-target="#myModal2">
                            Đăng Ký Ngay
                        </a>
                    </p>
                    @using (Ajax.BeginForm("DangNhap", "Home", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "thongbao" }))

                    {
                        <div class="styled-input agile-styled-input-top">
                            <input type="text" placeholder="Tài Khoản" name="TaiKhoan" required="">
                        </div>
                        <div class="styled-input">
                            <input type="password" placeholder="Mật Khẩu" name="MatKhau" required="">
                        </div>
                        <h3 style="color:green" id="thongbao">sfsd</h3>
                        <input type="submit" class="btnlogin" value="Đăng Nhập">
                    }

                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- //Modal content-->
    </div>
</div>

HaiSanShop.WebApp/Views/Home/TrangPhanHoi.cshtml
@{
    Layout=null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Trang Phản Hồi Quyền Truy Cập</title>
</head>
<body>
    <center>
        <div class="container">
            <h2>Bạn Không Đủ Quyền Để Truy Cập Trang Này, Vui Lòng Quay Về Trang Chủ</h2>
            @Html.ActionLink("Trang Chủ", "Index", "Home")
            
        </div>
    </center>
   
</body>
</html>

HaiSanShop.WebApp/Views/Home/contact.cshtml
@{
    ViewBag.Title = "Thông Tin Liên Hệ";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Đại Lý Hải Sản Sầm Sơn<br />
    34 Hồ Xuân Hương TP.Sầm Sơn<br />
    <abbr title="Phone">Phone:</abbr>
    0862560197
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:HaiSanSamSon@gamil.com">HaiSanSamSon@gamil.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing.HaiSanSamSon@gmail.com">Marketing.HaiSanSamSon@gmail.com</a>
</address>